-- MySQL Script generated by MySQL Workbench
-- Wed Mar 20 08:16:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema matin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema matin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matin` DEFAULT CHARACTER SET utf8 ;
USE `matin` ;

-- -----------------------------------------------------
-- Table `matin`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Local` (
  `CEP` INT NOT NULL AUTO_INCREMENT,
  `Logradouro` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CEP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Usuario` (
  `idUsu` INT NOT NULL AUTO_INCREMENT,
  `nome_usu` VARCHAR(50) NOT NULL,
  `ativo` ENUM('0', '1') NOT NULL DEFAULT '1',
  `data_criacao` DATE NOT NULL,
  `email_usu` VARCHAR(100) NOT NULL,
  `CPF_usu` VARCHAR(13) NOT NULL,
  `senha_usu` VARCHAR(45) NOT NULL,
  `tel_usu` VARCHAR(45) NOT NULL,
  `fotos_usu` VARCHAR(45) NULL,
  `premium` ENUM('0', '1') NOT NULL,
  `NR` VARCHAR(45) NOT NULL,
  `comp` VARCHAR(45) NOT NULL,
  `TCIR` ENUM('CPF', 'CNPJ') NOT NULL,
  `NRCIR` VARCHAR(45) NOT NULL,
  `nvl_usu` ENUM('A', 'F', 'C') NOT NULL DEFAULT 'C',
  `Local_CEP` INT NOT NULL,
  PRIMARY KEY (`idUsu`, `Local_CEP`),
  INDEX `fk_Usuario_Local_idx` (`Local_CEP` ASC),
  CONSTRAINT `fk_Usuario_Local`
    FOREIGN KEY (`Local_CEP`)
    REFERENCES `matin`.`Local` (`CEP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Avaliacao` (
  `id_aval` INT NOT NULL AUTO_INCREMENT,
  `avaliacao` INT(1) NOT NULL,
  `desc_aval` VARCHAR(100) NOT NULL,
  `data_aval` DATE NOT NULL,
  `preco_aval` DECIMAL(5,2) NOT NULL,
  `likes` INT NOT NULL DEFAULT 0,
  `deslikes` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_aval`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Faz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Faz` (
  `Usuario_idUsu` INT NOT NULL,
  `Avaliacao_id_aval` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsu`, `Avaliacao_id_aval`),
  INDEX `fk_Usuario_has_Avaliacao_Avaliacao1_idx` (`Avaliacao_id_aval` ASC),
  INDEX `fk_Usuario_has_Avaliacao_Usuario1_idx` (`Usuario_idUsu` ASC),
  CONSTRAINT `fk_Usuario_has_Avaliacao_Usuario1`
    FOREIGN KEY (`Usuario_idUsu`)
    REFERENCES `matin`.`Usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Avaliacao_Avaliacao1`
    FOREIGN KEY (`Avaliacao_id_aval`)
    REFERENCES `matin`.`Avaliacao` (`id_aval`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Pergunta` (
  `idPergunta` INT NOT NULL AUTO_INCREMENT,
  `desc_perg` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPergunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Usuario_has_Pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Usuario_has_Pergunta` (
  `Usuario_idUsu` INT NOT NULL,
  `Pergunta_idPergunta` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsu`, `Pergunta_idPergunta`),
  INDEX `fk_Usuario_has_Pergunta_Pergunta1_idx` (`Pergunta_idPergunta` ASC),
  INDEX `fk_Usuario_has_Pergunta_Usuario1_idx` (`Usuario_idUsu` ASC),
  CONSTRAINT `fk_Usuario_has_Pergunta_Usuario1`
    FOREIGN KEY (`Usuario_idUsu`)
    REFERENCES `matin`.`Usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Pergunta_Pergunta1`
    FOREIGN KEY (`Pergunta_idPergunta`)
    REFERENCES `matin`.`Pergunta` (`idPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome_prod` VARCHAR(100) NOT NULL,
  `qnt_prod_estoque` INT NOT NULL,
  `data_criacao_prod` DATE NOT NULL,
  `preco_prod` DECIMAL(5,2) NOT NULL,
  `fotos_prod` VARCHAR(100) NOT NULL DEFAULT 'sem_foto.png',
  `qnt_vendas` INT NOT NULL,
  `promocao` INT NULL,
  `parcela` INT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Avaliacao_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Avaliacao_has_Produto` (
  `Avaliacao_id_aval` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Avaliacao_id_aval`, `Produto_idProduto`),
  INDEX `fk_Avaliacao_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Avaliacao_has_Produto_Avaliacao1_idx` (`Avaliacao_id_aval` ASC),
  CONSTRAINT `fk_Avaliacao_has_Produto_Avaliacao1`
    FOREIGN KEY (`Avaliacao_id_aval`)
    REFERENCES `matin`.`Avaliacao` (`id_aval`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `matin`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`NPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`NPedido` (
  `Usuario_idUsu` INT NOT NULL,
  `Usuario_Local_CEP` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `situacao` ENUM('0', '1') NOT NULL,
  `data_criacao` DATE NOT NULL,
  `qnt_pedida` INT NOT NULL,
  `tipoqnt_ped` ENUM('kg', 'unid') NOT NULL,
  PRIMARY KEY (`Usuario_idUsu`, `Usuario_Local_CEP`, `Produto_idProduto`),
  INDEX `fk_Usuario_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Usuario_has_Produto_Usuario1_idx` (`Usuario_idUsu` ASC, `Usuario_Local_CEP` ASC),
  CONSTRAINT `fk_Usuario_has_Produto_Usuario1`
    FOREIGN KEY (`Usuario_idUsu` , `Usuario_Local_CEP`)
    REFERENCES `matin`.`Usuario` (`idUsu` , `Local_CEP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `matin`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Pergunta_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Pergunta_has_Produto` (
  `Pergunta_idPergunta` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Pergunta_idPergunta`, `Produto_idProduto`),
  INDEX `fk_Pergunta_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Pergunta_has_Produto_Pergunta1_idx` (`Pergunta_idPergunta` ASC),
  CONSTRAINT `fk_Pergunta_has_Produto_Pergunta1`
    FOREIGN KEY (`Pergunta_idPergunta`)
    REFERENCES `matin`.`Pergunta` (`idPergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pergunta_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `matin`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nome_cat` VARCHAR(45) NOT NULL,
  `img_cat` VARCHAR(300) NULL,
  `desc_cat` VARCHAR(100) NULL,
  `qnt_vis` INT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Produto_has_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Produto_has_Categoria` (
  `Produto_idProduto` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Categoria_idCategoria`),
  INDEX `fk_Produto_has_Categoria_Categoria1_idx` (`Categoria_idCategoria` ASC),
  INDEX `fk_Produto_has_Categoria_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Produto_has_Categoria_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `matin`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `matin`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Seguidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Seguidores` (
  `idSeguidor` INT NOT NULL,
  `qntSeguidor` INT NULL,
  PRIMARY KEY (`idSeguidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matin`.`Seguidores_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matin`.`Seguidores_has_Usuario` (
  `Seguidores_idSeguidor` INT NOT NULL,
  `Usuario_idUsu` INT NOT NULL,
  PRIMARY KEY (`Seguidores_idSeguidor`, `Usuario_idUsu`),
  INDEX `fk_Seguidores_has_Usuario_Usuario1_idx` (`Usuario_idUsu` ASC),
  INDEX `fk_Seguidores_has_Usuario_Seguidores1_idx` (`Seguidores_idSeguidor` ASC),
  CONSTRAINT `fk_Seguidores_has_Usuario_Seguidores1`
    FOREIGN KEY (`Seguidores_idSeguidor`)
    REFERENCES `matin`.`Seguidores` (`idSeguidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seguidores_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsu`)
    REFERENCES `matin`.`Usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
